### ISSUE TITLE
module.js:549

### ISSUE THREAD

**Issue by neoll4ik** [AnIdiotsGuide/guidebot-class#25]
node setup.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/neoll/BOTS/guidebot-class/setup.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by MrJacz** [comment]
The error is in english, `setup.js` doesnt exist in guidebot-class

**Comment by neoll4ik** [comment]
try reinstall and npm -g --unsafe-perm install node-sass

now got  
node util/setup.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/util.setup.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by neoll4ik** [comment]
try npm -g --unsafe-perm install node-sass

and got 

node /util/setup.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/util/setup.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by YorkAARGH** [comment]
The setup should run automatically when you install the bot, nothing has changed for that functionality, and what are you installing globally? That has nothing to do with guidebot-class

**Comment by YorkAARGH** [comment]
Closed due to not being able to reproduce.
